name: Flutter CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Create .env file
        run: |
          echo "API_KEY = ${{ secrets.API_KEY }}" > .env

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release


